### ISSUE TITLE
Errors on the map page

### ISSUE THREAD

**Issue by roddyyaga** [o1-labs/ocamlbyexample#1]
Hey, I spotted a few mistakes on the page about maps (https://o1-labs.github.io/ocamlbyexample/basics-map.html)

- Maps in Core are not hashmaps, they are implemented with search trees. There are various important differences between the two, for instance in a hash table the keys must be hashable but in a search tree they need to be comparable instead. Core does have hashmaps as well in the `Hashtbl` module.
- "dictionnaries" has an extra n

Also, in the example code `let balances = Map.empty (module String)` I think it would be more idiomatic to do `let balances = String.Map.empty`. Many modules like `String` in Core have a specialised map submodule like this.

**Comment by mimoo** [comment]
Hey! Sorry for the slow reply, and thanks for pointing these out. Would you be interested in submitting a PR to provide these changes?
